version: '3.7'

services:
  web:
    build: .
    container_name: web_service
    command: gunicorn app.wsgi:application --bind 0.0.0.0:7000
#    command: python manage.py runserver 0.0.0.0:86
    volumes:
      - static_volum:/usr/src/static
      - media_volum:/usr/src/media
    ports:
      - 7000:7000
    env_file:
      - .web_env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: db_service
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5439:5432
    env_file:
      - .db_env.dev

  nginx:
    build: ./nginx
    container_name: nginx_service
    volumes:
      - static_volum:/usr/src/static
      - media_volum:/usr/src/media
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
    name: db_data
  static_volum:
  media_volum:
